### ISSUE TITLE
FluidNC Dokumentation fehler

### ISSUE THREAD

**Issue by luft-post** [timo1235/docs#2]
Moin,

auf https://docs.timos-werkstatt.de/open-cnc-shield-2/controllermodules/fluidnc beim Shift Register ist die Angabe von i2so.9 falsch.
OCS2 DIR A muss OCS2 DIR B lauten.

gruß
Matthias

**Comment by timo1235** [comment]
Moin,
du hast recht. Ich habe es direkt angepasst. Vielen Dank für den Hinweis und die Unterstützung 

Fixed with [994e8c5324b6f00fb9941dd50112c13ff9ab32ec](https://github.com/timo1235/docs/commit/994e8c5324b6f00fb9941dd50112c13ff9ab32ec)

**Comment by luft-post** [comment]
in deiner Beispiel FluidNC Konfiguration, unter "z:" und "Motor1" steht "null_motor:" das ist glaube auch nicht richtig, zumindest finde ich es unter http://wiki.fluidnc.com nicht.

gruß
Matthias

**Comment by timo1235** [comment]
Das ist okay. Sollte auch so angezeigt werden, wenn du die FLuidNC konsole laufen hast und FluidNC neustartest. Dann gibt er ja die ganze Config aus. Das ist ein default wert, welcher anzeigt, dass es da keinen motor gibt. 

Edit: Kannste auch weglassen.
